---
# tasks file for nginx-role
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable Nginx service
  service: 
    name: nginx    
    enabled: yes

- name: Deploy webpage content
  copy:
    src: index.html
    dest: /var/www/html
  